baseurl = "https://stefanreifenberg.github.io/"
languageCode = "en-us"
theme = "hello-friend-ng"
#publishDir = "stefanreifenberg.ithub.io"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Stefan Reifenberg"
  keywords = "homepage, blog, science, informatics, development, programming, dataviz, erlang, R, shiny"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  homeSubtitle = "Developer, Scientist, Dataviz lover"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/Reyfenberg"

  [[params.social]]
    name = "email"
    url  = "mailto:stefan.reifenberg@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/stefanreifenberg"


[languages]
  [languages.en]
    title = "Stefan Reifenberg"
    subtitle = "Test"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = ""

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/post"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
